ALTER TYPE "AiProviderKind" ADD VALUE IF NOT EXISTS 'MIKOTO';
ALTER TYPE "AiProviderKind" ADD VALUE IF NOT EXISTS 'BIGMODEL';

ALTER TYPE "AiCapability" ADD VALUE IF NOT EXISTS 'IMAGE_NANO_BANANA_PRO_1K';
ALTER TYPE "AiCapability" ADD VALUE IF NOT EXISTS 'IMAGE_GPT_1K';
